### ISSUE TITLE
管理画面の挙動

### ISSUE THREAD

**Issue by Lisitsa-requin** [Xeltica/Groundpolis#101]
一度モデレーター権限を付与されたアカウントでログインしていると、権限が無くなったあとでも、リンクを直接叩くことによってダッシュボードを見れてしまう

**Comment by Xeltica** [comment]
ダッシュボード自体はマジで一般ユーザーでもURLから見れてしまう（Misskeyの仕様っぽい）けど、機密情報は取得できないようになっているのでまあ大丈夫かなあと

**Comment by Lisitsa-requin** [comment]
お知らせとかいじれそうな感じだけど実際にやると反映はされないのかな

**Comment by Xeltica** [comment]
何か挙動気持ち悪いけど裏技として仕様にしたいので管理者でない場合イジる系の項目を出ないようにします...

**Comment by Lisitsa-requin** [comment]
了解
じゃあピを閉めます

**Comment by Xeltica** [comment]
閉じないで💢

**Comment by Lisitsa-requin** [comment]
すまんこ

**Comment by Xeltica** [comment]
やはり、一般ユーザーは閲覧できない画面にします
