### ISSUE TITLE
フォローしていないアカウントのフォロワー限定投稿がGTLに流れてしまう

### ISSUE THREAD

**Issue by silverscat-3** [Xeltica/Groundpolis#113]
## 💡 Summary
読んで字の如く。

## 🙂 Expected Behavior
フォロワー限定投稿はHTLかSTLにしか流れないはず

## ☹️ Actual Behavior
GTLで、しかもフォローしていないアカウントのフォロワー限定投稿が見えてしまう

**Comment by Xeltica** [comment]
完全に理解したので修正版出しますわゾ

**Comment by Xeltica** [comment]
603da68 fixed
