### ISSUE TITLE
プロフィールに性別を表示

### ISSUE THREAD

**Issue by silverscat-3** [Xeltica/Groundpolis#39]
ロクなことに使われなさそうだけど、とりあえずあってもいいかなと

**Comment by silverscat-3** [comment]
保存する形式としては、[ISO 5218](https://ja.wikipedia.org/wiki/ISO_5218)を用いましょう。

**Comment by silverscat-3** [comment]
not known(不明)は「未回答」または「未設定」、not applicable(適用不能)は「その他」としてFacebookみたいに好きなテキストを入れれるといいですね(でもどういうテキストを入れるんだろう…?)

**Comment by Xeltica** [comment]
|コード|日本語での表示|
|------|---------------|
|0       |無し(項目が表示されない)|
|1        |男                     |
|2       |女                      |
|9       |その他               |

で十分だと思うのでそれで
