### ISSUE TITLE
用語をマストドンに寄せたり変えたり

### ISSUE THREAD

**Issue by Xeltica** [Xeltica/Groundpolis#43]
+ 投稿 → トゥート
+ リノート→ブースト
+ ソーシャル→ホーム+ローカル
+ 公開範囲
  + ホーム→未収載
  + フォロワー→フォロワー限定
+ グローバルタイムライン → 連合タイムライン
+ インスタンス→サーバー

**Comment by Xeltica** [comment]
個人的にマストドンのシェアからして用語を合わせたほうが交流がしやすそうという気持ち

**Comment by silverscat-3** [comment]
MisskeyとMastodonは別物なので無理に合わせる必要性もないのではないでしょうか? 実際、Pleromaでも違いますしね。

**Comment by Xeltica** [comment]
まあユーザーがどう呼ぶかの問題にまかせて公式での用語改変はやめたほうがよさそうですね
