### ISSUE TITLE
紛らわしい絵文字ボタンと顔文字ボタンをなんとかしたい

### ISSUE THREAD

**Issue by ijs01140** [Xeltica/Groundpolis#73]
現状だと、絵文字ボタンと顔文字ボタンが紛らわしすぎるので、わかりやすくしたい
![image](https://user-images.githubusercontent.com/24949850/64078341-88393000-cd14-11e9-87d8-63f95a16cfc6.png)

例えば、こんな感じに変更するとわかりやすくなりそう
![image](https://user-images.githubusercontent.com/24949850/64078387-e6661300-cd14-11e9-914b-ea7a75862226.png)

**Comment by acid-chicken** [comment]
FYI: twista では faCat を使用しています。
![image](https://user-images.githubusercontent.com/20679825/64078414-51174e80-cd15-11e9-8352-0673ca6d8625.png)

**Comment by Xeltica** [comment]
フグパンチが代名詞感あるのでフグのアイコンあったらいいんだけど

**Comment by Xeltica** [comment]
ひとまずねこにします
