### ISSUE TITLE
ミュート、ブロックした人の投稿をTLにそっと表示するオプション

### ISSUE THREAD

**Issue by silverscat-3** [Xeltica/Groundpolis#90]
## Summary

ブロックしている人の投稿が表示されない影響で、RNに言及してるときなどに何を言っているのかわからなくなるときがある。
なので、小さくTLに「ブロックしたアカウントの投稿です。表示しますか?」と表示する機能があってもいいかもしれない。
これを強制すると面倒なことになりそうなので設定でオンオフできるようにするべきだと思う。

**Comment by tkmrgit** [comment]
なるほど。個人的な意見ですが、ミュート・ブロック言及については見てあとでなんともいえないことになることがtwitterでも多いのでその引用投稿自体が無かったことになるほうが望ましいです。

**Comment by Xeltica** [comment]
Discordの仕様に近いですね。個人的にはあまり欲しくない機能なのと、実装するとしたらisMutedみたいなプロパティを投稿に生やす必要があり、APIレベルではミュートしたノートが取得できてしまう破壊的変更になり得るのでアレなのと、地味に実装が面倒そうです...

**Comment by Xeltica** [comment]
グランポリスはデフォルトで引用フォームが表示されているように引用RNを推奨しており、また別issueで引用RNがmuted userへの言及であれば同じく表示されないようにする予定なので（そもそもミュートしたユーザーの投稿を表示するかどうか聞くのは本末転倒っぽい）closeします...
